Repository datacarpentry/r-socialsci, pull requests merged in 2020-09, with the labels that each got.

#244 clarify the phrase 'in-memory' and fix a typo
  _episodes_rmd/.ignore-05-databases.Rmd
Labels: good first issue, type:clarification

#242 Introduction to Long/Wide Data
  _episodes_rmd/03-dplyr-tidyr.Rmd
  fig/tidyr-pivot_wider_longer.gif
Labels: high priority, type:enhancement

#235 Update 04-ggplot2.Rmd - use geom_count instead of geom_jitter
  _episodes_rmd/04-ggplot2.Rmd
Labels: type:discussion

#182 change words to British spelling conventions
  _episodes_rmd/03-dplyr-tidyr.Rmd
  _episodes_rmd/04-ggplot2.Rmd
Labels: status:in progress
